// lib/learnfun/constants.ts

import { Badge, GameType, LearnFunGame, Skill, SkillWorld } from "./types";

// ─── XP CONFIG ────────────────────────────────────────────────────────────────
export const XP_PER_LEVEL = 200;

export function getLevelFromXP(xp: number): number {
  return Math.floor(xp / XP_PER_LEVEL) + 1;
}

// ─── DAILY SKILL ROTATION (by day of week) ────────────────────────────────────
export const DAILY_SKILL_ROTATION: Record<number, Skill | "boss_battle"> = {
  1: "Money Management",
  2: "Time Management",
  3: "Digital Safety",
  4: "Decision Making",
  5: "boss_battle",
  6: "Career Awareness",
  0: "Goal Setting",
};

// ─── GAMES (28 total, 4 per class 6-12) ───────────────────────────────────────
export const GAMES: LearnFunGame[] = [
  // ── Class 6 ──────────────────────────────────────────────────────────────────
  {
    id: "c6_budget_1",
    title: "Savings Jar Challenge",
    classRange: [6],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "easy",
    durationMinutes: 8,
    description: "Fill your savings jar by making smart spending choices every day!",
    emoji: "🏺",
    gradientColors: ["#F59E0B", "#F97316"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c6_time_1",
    title: "After School Planner",
    classRange: [6],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "easy",
    durationMinutes: 8,
    description: "Plan your after-school hours — homework, tuition, play and dinner!",
    emoji: "📚",
    gradientColors: ["#10B981", "#34D399"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c6_choice_1",
    title: "Team Mission Camp",
    classRange: [6],
    skill: "Communication",
    gameType: "choice_story",
    difficulty: "easy",
    durationMinutes: 7,
    description: "You are on a school camp. Work as a team to complete all missions!",
    emoji: "⛺",
    gradientColors: ["#8B5CF6", "#A78BFA"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c6_digital_1",
    title: "Screen Time Balance",
    classRange: [6],
    skill: "Digital Safety",
    gameType: "digital_safety",
    difficulty: "easy",
    durationMinutes: 7,
    description: "Balance your screen time — games, study apps and safe browsing!",
    emoji: "📱",
    gradientColors: ["#0EA5E9", "#6366F1"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 7 ──────────────────────────────────────────────────────────────────
  {
    id: "c7_budget_1",
    title: "Smart Buyer Market",
    classRange: [7],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "medium",
    durationMinutes: 10,
    description: "Visit the market with ₹200. Compare prices and make smart purchases!",
    emoji: "🏪",
    gradientColors: ["#F59E0B", "#EF4444"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c7_time_1",
    title: "Exam Week Planner",
    classRange: [7],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "medium",
    durationMinutes: 10,
    description: "Exams are coming! Create a study timetable that covers all subjects.",
    emoji: "📝",
    gradientColors: ["#10B981", "#059669"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c7_choice_1",
    title: "Friendship Choice Game",
    classRange: [7],
    skill: "Emotional Control",
    gameType: "choice_story",
    difficulty: "medium",
    durationMinutes: 9,
    description: "Navigate friendship situations at school. Choose words carefully!",
    emoji: "🤝",
    gradientColors: ["#EC4899", "#F43F5E"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c7_digital_1",
    title: "Fake Link Detector",
    classRange: [7],
    skill: "Digital Safety",
    gameType: "digital_safety",
    difficulty: "medium",
    durationMinutes: 9,
    description: "Spot fake links, scam messages and unsafe websites before clicking!",
    emoji: "🔍",
    gradientColors: ["#EF4444", "#B91C1C"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 8 ──────────────────────────────────────────────────────────────────
  {
    id: "c8_budget_1",
    title: "Budget Boss Junior",
    classRange: [8],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "medium",
    durationMinutes: 12,
    description: "Manage ₹500 for a week. Handle emergencies and still save!",
    emoji: "💰",
    gradientColors: ["#F59E0B", "#D97706"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c8_time_1",
    title: "Mission 24 Hours",
    classRange: [8],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "medium",
    durationMinutes: 12,
    description: "Plan your entire day across 24 hours — not one minute wasted!",
    emoji: "⏰",
    gradientColors: ["#0EA5E9", "#0284C7"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c8_career_1",
    title: "Goal Mountain",
    classRange: [8],
    skill: "Goal Setting",
    gameType: "career_goal",
    difficulty: "medium",
    durationMinutes: 10,
    description: "Climb Goal Mountain by setting clear targets and planning each step!",
    emoji: "⛰️",
    gradientColors: ["#8B5CF6", "#7C3AED"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c8_digital_1",
    title: "Cyber Shield",
    classRange: [8],
    skill: "Digital Safety",
    gameType: "digital_safety",
    difficulty: "medium",
    durationMinutes: 10,
    description: "Protect your family from cyber threats using your Cyber Shield!",
    emoji: "🛡️",
    gradientColors: ["#EF4444", "#DC2626"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 9 ──────────────────────────────────────────────────────────────────
  {
    id: "c9_budget_1",
    title: "Banking Basics Game",
    classRange: [9],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "medium",
    durationMinutes: 12,
    description: "Open a savings account, deposit wisely and track your balance!",
    emoji: "🏦",
    gradientColors: ["#10B981", "#059669"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c9_time_1",
    title: "Board Prep Starter",
    classRange: [9],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Start your Class 10 prep early. Build a 3-month study calendar!",
    emoji: "📅",
    gradientColors: ["#F59E0B", "#D97706"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c9_career_1",
    title: "Career City Explorer",
    classRange: [9],
    skill: "Career Awareness",
    gameType: "career_goal",
    difficulty: "medium",
    durationMinutes: 12,
    description: "Explore Career City — visit different professions and find your calling!",
    emoji: "🏙️",
    gradientColors: ["#8B5CF6", "#6366F1"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c9_digital_1",
    title: "Privacy Defender",
    classRange: [9],
    skill: "Digital Safety",
    gameType: "digital_safety",
    difficulty: "hard",
    durationMinutes: 13,
    description: "Defend your personal data from hackers and privacy invaders!",
    emoji: "🔒",
    gradientColors: ["#0EA5E9", "#0284C7"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 10 ─────────────────────────────────────────────────────────────────
  {
    id: "c10_budget_1",
    title: "Family Budget Simulator",
    classRange: [10],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Manage the family's monthly budget of ₹15,000. Bills, food, savings!",
    emoji: "👨‍👩‍👧",
    gradientColors: ["#F59E0B", "#B45309"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c10_time_1",
    title: "90-Day Board Challenge",
    classRange: [10],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Build a 90-day Board exam prep plan. Balance all subjects perfectly!",
    emoji: "🎯",
    gradientColors: ["#EF4444", "#DC2626"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c10_career_1",
    title: "Stream Selection Quest",
    classRange: [10],
    skill: "Career Awareness",
    gameType: "career_goal",
    difficulty: "hard",
    durationMinutes: 14,
    description: "Choose your stream wisely — Science, Commerce or Arts. Explore each!",
    emoji: "🗺️",
    gradientColors: ["#8B5CF6", "#4C1D95"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c10_digital_1",
    title: "Digital Footprint Mission",
    classRange: [10],
    skill: "Digital Safety",
    gameType: "digital_safety",
    difficulty: "hard",
    durationMinutes: 13,
    description: "Your digital footprint follows you forever. Clean it up and stay safe!",
    emoji: "👣",
    gradientColors: ["#0EA5E9", "#1D4ED8"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 11 ─────────────────────────────────────────────────────────────────
  {
    id: "c11_budget_1",
    title: "Money Master Level 1",
    classRange: [11],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Advanced money management — SIPs, insurance and emergency funds!",
    emoji: "💎",
    gradientColors: ["#F59E0B", "#92400E"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c11_time_1",
    title: "Productivity Planner",
    classRange: [11],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Ace both Board and entrance exams. Build a smart productivity system!",
    emoji: "⚡",
    gradientColors: ["#10B981", "#065F46"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c11_career_1",
    title: "Career Path Builder",
    classRange: [11],
    skill: "Career Awareness",
    gameType: "career_goal",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Build your career roadmap — college, skills and first job milestones!",
    emoji: "🚀",
    gradientColors: ["#8B5CF6", "#3730A3"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c11_choice_1",
    title: "Group Discussion Game",
    classRange: [11],
    skill: "Communication",
    gameType: "choice_story",
    difficulty: "hard",
    durationMinutes: 12,
    description: "Participate in a GD round. Choose what to say and when to say it!",
    emoji: "🎤",
    gradientColors: ["#EC4899", "#BE185D"],
    isActive: true,
    isComingSoon: false,
  },

  // ── Class 12 ─────────────────────────────────────────────────────────────────
  {
    id: "c12_budget_1",
    title: "Personal Finance Simulator",
    classRange: [12],
    skill: "Money Management",
    gameType: "budget_simulator",
    difficulty: "boss",
    durationMinutes: 20,
    description: "Manage your first salary of ₹25,000. Rent, food, savings and fun!",
    emoji: "🏛️",
    gradientColors: ["#F59E0B", "#78350F"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c12_time_1",
    title: "Board + Entrance Planner",
    classRange: [12],
    skill: "Time Management",
    gameType: "time_planner",
    difficulty: "boss",
    durationMinutes: 20,
    description: "Balance Class 12 boards and JEE/NEET prep in one mega study plan!",
    emoji: "📖",
    gradientColors: ["#EF4444", "#7F1D1D"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c12_career_1",
    title: "College & Career Planner",
    classRange: [12],
    skill: "Career Awareness",
    gameType: "career_goal",
    difficulty: "boss",
    durationMinutes: 18,
    description: "Plan your college applications, entrance exams and gap year options!",
    emoji: "🎓",
    gradientColors: ["#8B5CF6", "#2E1065"],
    isActive: true,
    isComingSoon: false,
  },
  {
    id: "c12_choice_1",
    title: "Interview Room",
    classRange: [12],
    skill: "Communication",
    gameType: "choice_story",
    difficulty: "boss",
    durationMinutes: 15,
    description: "Face your first college interview. Choose your words, ace every answer!",
    emoji: "👔",
    gradientColors: ["#0EA5E9", "#1E3A5F"],
    isActive: true,
    isComingSoon: false,
  },
];

// ─── COMING SOON GAMES ────────────────────────────────────────────────────────
export const COMING_SOON: LearnFunGame[] = [
  {
    id: "cs_leadership_1",
    title: "Leadership Challenge",
    classRange: [6, 7, 8, 9, 10, 11, 12],
    skill: "Leadership",
    gameType: "choice_story",
    difficulty: "medium",
    durationMinutes: 12,
    description: "Lead your team through challenges. Inspire, decide and deliver!",
    emoji: "👑",
    gradientColors: ["#818CF8", "#4338CA"],
    isActive: false,
    isComingSoon: true,
  },
  {
    id: "cs_startup_1",
    title: "Startup Founder",
    classRange: [6, 7, 8, 9, 10, 11, 12],
    skill: "Decision Making",
    gameType: "career_goal",
    difficulty: "hard",
    durationMinutes: 15,
    description: "Start your own company from zero. Hire, market and grow!",
    emoji: "🦄",
    gradientColors: ["#F59E0B", "#F97316"],
    isActive: false,
    isComingSoon: true,
  },
  {
    id: "cs_stress_1",
    title: "Stress Balance Mission",
    classRange: [6, 7, 8, 9, 10, 11, 12],
    skill: "Emotional Control",
    gameType: "choice_story",
    difficulty: "medium",
    durationMinutes: 10,
    description: "Keep your stress levels balanced using healthy coping strategies!",
    emoji: "🧘",
    gradientColors: ["#10B981", "#34D399"],
    isActive: false,
    isComingSoon: true,
  },
  {
    id: "cs_speaking_1",
    title: "Public Speaking Stage",
    classRange: [6, 7, 8, 9, 10, 11, 12],
    skill: "Communication",
    gameType: "choice_story",
    difficulty: "hard",
    durationMinutes: 12,
    description: "Stand on stage and speak confidently to hundreds of people!",
    emoji: "🎙️",
    gradientColors: ["#EC4899", "#BE185D"],
    isActive: false,
    isComingSoon: true,
  },
];

// ─── SKILL WORLDS ─────────────────────────────────────────────────────────────
export const SKILL_WORLDS: SkillWorld[] = [
  {
    id: "world_money",
    name: "Money World",
    emoji: "💰",
    skill: "Money Management",
    gradientColors: ["#F59E0B", "#D97706"],
    locked: false,
  },
  {
    id: "world_time",
    name: "Time World",
    emoji: "⏰",
    skill: "Time Management",
    gradientColors: ["#10B981", "#059669"],
    locked: false,
  },
  {
    id: "world_cyber",
    name: "Cyber World",
    emoji: "🛡️",
    skill: "Digital Safety",
    gradientColors: ["#0EA5E9", "#0284C7"],
    locked: false,
  },
  {
    id: "world_goal",
    name: "Goal World",
    emoji: "⛰️",
    skill: "Goal Setting",
    gradientColors: ["#8B5CF6", "#6366F1"],
    locked: false,
  },
  {
    id: "world_career",
    name: "Career World",
    emoji: "🚀",
    skill: "Career Awareness",
    gradientColors: ["#EC4899", "#BE185D"],
    locked: true,
  },
  {
    id: "world_comm",
    name: "Communication World",
    emoji: "🎤",
    skill: "Communication",
    gradientColors: ["#F97316", "#EA580C"],
    locked: true,
  },
  {
    id: "world_health",
    name: "Health World",
    emoji: "💪",
    skill: "Health & Habits",
    gradientColors: ["#10B981", "#065F46"],
    locked: true,
  },
  {
    id: "world_lead",
    name: "Leadership World",
    emoji: "👑",
    skill: "Leadership",
    gradientColors: ["#818CF8", "#4338CA"],
    locked: true,
  },
];

// ─── BADGES ───────────────────────────────────────────────────────────────────
export const BADGES: Badge[] = [
  {
    id: "badge_money_saver",
    name: "Money Saver",
    description: "Completed your first budget mission without overspending",
    emoji: "💰",
    skill: "Money Management",
  },
  {
    id: "badge_time_wizard",
    name: "Time Wizard",
    description: "Built a perfect daily schedule without any conflicts",
    emoji: "⏰",
    skill: "Time Management",
  },
  {
    id: "badge_cyber_guard",
    name: "Cyber Guardian",
    description: "Identified all phishing attempts correctly",
    emoji: "🛡️",
    skill: "Digital Safety",
  },
  {
    id: "badge_goal_setter",
    name: "Goal Setter",
    description: "Set 3 SMART goals and mapped out action steps",
    emoji: "🎯",
    skill: "Goal Setting",
  },
  {
    id: "badge_career_explorer",
    name: "Career Explorer",
    description: "Explored 5 different career paths",
    emoji: "🚀",
    skill: "Career Awareness",
  },
  {
    id: "badge_good_choice",
    name: "Good Choice Maker",
    description: "Made the right decision in every story chapter",
    emoji: "✅",
    skill: "Decision Making",
  },
  {
    id: "badge_streak_7",
    name: "7 Day Streak Hero",
    description: "Completed missions 7 days in a row",
    emoji: "🔥",
    skill: "Health & Habits",
  },
  {
    id: "badge_boss_slayer",
    name: "Boss Slayer",
    description: "Defeated the weekly Boss Battle with full marks",
    emoji: "⚔️",
    skill: "Leadership",
  },
  {
    id: "badge_communicator",
    name: "Master Communicator",
    description: "Aced the Group Discussion or Interview game",
    emoji: "🎤",
    skill: "Communication",
  },
  {
    id: "badge_emotion_master",
    name: "Emotion Master",
    description: "Handled every friendship challenge with empathy",
    emoji: "❤️",
    skill: "Emotional Control",
  },
];

// ─── FALLBACK MISSIONS (when no class-specific mission is found) ───────────────
export const FALLBACK_MISSIONS_IDS = [
  "fallback_money_basics",
  "fallback_time_basics",
  "fallback_digital_basics",
  "fallback_goal_basics",
];
