// PATH: app/billing-history.tsx
//
// Customer-facing billing history — lists the signed-in student's own
// subscription invoices via services/billingService.ts's getMyInvoices()
// (functions/src/billingHistory.ts). Read-only: this screen never writes
// to invoices/ (client writes are closed — see firestore.rules) and never
// passes a uid/target-user to the backend; ownership is enforced entirely
// server-side by context.auth.uid.

import Header from "@/components/header";
import { useAppTranslation } from "@/context/LanguageContext";
import { useTheme } from "@/context/ThemeContext";
import {
  formatInvoiceAmount,
  formatInvoiceDate,
  getMyInvoices,
  invoiceStatusLabel,
  planDisplayName,
  type InvoiceRecord,
} from "@/services/billingService";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  ActivityIndicator,
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const PAGE_SIZE = 10;

type ScreenState = "loading" | "ready" | "error";

function statusVisual(status: string): { color: string; icon: keyof typeof Ionicons.glyphMap } {
  switch (status) {
    case "paid":    return { color: "#22C55E", icon: "checkmark-circle" };
    case "pending": return { color: "#f59e0b", icon: "time-outline" };
    case "failed":  return { color: "#ef4444", icon: "close-circle" };
    default:        return { color: "#94a3b8", icon: "help-circle-outline" };
  }
}

export default function BillingHistoryScreen() {
  const { colors, isDarkMode } = useTheme();
  const { t } = useAppTranslation();
  const router = useRouter();

  const [state,        setState]        = useState<ScreenState>("loading");
  const [invoices,     setInvoices]     = useState<InvoiceRecord[]>([]);
  const [hasMore,      setHasMore]      = useState(false);
  const [cursor,       setCursor]       = useState<string | null>(null);
  const [loadingMore,  setLoadingMore]  = useState(false);
  const [pageError,    setPageError]    = useState(false);
  // Guards against a second onEndReached firing while the first request
  // for the next page is still in flight (FlatList can fire it more than
  // once during momentum scroll) — the actual duplicate-request guard,
  // not just a UI nicety.
  const fetchingRef = useRef(false);

  const loadFirstPage = useCallback(async () => {
    setState("loading");
    try {
      const result = await getMyInvoices({ pageSize: PAGE_SIZE });
      setInvoices(result.invoices);
      setHasMore(result.hasMore);
      setCursor(result.nextCursor);
      setState("ready");
    } catch {
      setState("error");
    }
  }, []);

  useEffect(() => { loadFirstPage(); }, [loadFirstPage]);

  const loadNextPage = useCallback(async () => {
    if (!hasMore || !cursor || fetchingRef.current) return;
    fetchingRef.current = true;
    setLoadingMore(true);
    setPageError(false);
    try {
      const result = await getMyInvoices({ pageSize: PAGE_SIZE, startAfterInvoiceId: cursor });
      setInvoices((prev) => [...prev, ...result.invoices]);
      setHasMore(result.hasMore);
      setCursor(result.nextCursor);
    } catch {
      // Next-page failure doesn't blow away what's already loaded —
      // just surface a retryable footer, same idea as the top-level
      // error state but scoped to pagination only.
      setPageError(true);
    } finally {
      fetchingRef.current = false;
      setLoadingMore(false);
    }
  }, [hasMore, cursor]);

  const openInvoice = (invoice: InvoiceRecord) => {
    // "as any" — same established workaround profile-settings.tsx already
    // uses for a route not yet reflected in the generated
    // .expo/types/router.d.ts (regenerated by `expo start`, not by hand);
    // /invoice-details is a real route (see app/invoice-details.tsx).
    router.push({ pathname: "/invoice-details" as any, params: { invoice: JSON.stringify(invoice) } });
  };

  const surfaceBg = isDarkMode ? "#1e293b" : colors.card;
  const borderCol = isDarkMode ? "#334155" : colors.border;
  const pageBg    = isDarkMode ? "#0a0a1a" : colors.background;

  const renderItem = ({ item }: { item: InvoiceRecord }) => {
    const visual = statusVisual(item.status);
    return (
      <TouchableOpacity
        style={[styles.card, { backgroundColor: surfaceBg, borderColor: borderCol }]}
        onPress={() => openInvoice(item)}
        activeOpacity={0.75}
        accessibilityRole="button"
        accessibilityLabel={`Invoice ${item.invoiceId}, ${planDisplayName(item)}, ${formatInvoiceAmount(item.totalAmountPaise, item.currency)}, status ${invoiceStatusLabel(item.status)}`}
      >
        <View style={styles.cardTop}>
          <Text style={[styles.planName, { color: colors.text }]} numberOfLines={1}>
            {planDisplayName(item)}
          </Text>
          <View style={[styles.statusPill, { backgroundColor: `${visual.color}1a` }]}>
            <Ionicons name={visual.icon} size={13} color={visual.color} accessibilityElementsHidden />
            <Text style={[styles.statusText, { color: visual.color }]}>{invoiceStatusLabel(item.status)}</Text>
          </View>
        </View>

        <Text style={[styles.invoiceNumber, { color: colors.textSecondary }]} numberOfLines={1}>
          {t("invoiceNumber") ?? "Invoice"} #{item.invoiceId}
        </Text>

        <View style={styles.cardBottom}>
          <Text style={[styles.date, { color: colors.textSecondary }]}>{formatInvoiceDate(item.paidAt ?? item.issuedAt)}</Text>
          <Text style={[styles.amount, { color: colors.text }]}>{formatInvoiceAmount(item.totalAmountPaise, item.currency)}</Text>
        </View>
      </TouchableOpacity>
    );
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: pageBg }]}>
      <Header hideMenu={true} />

      <View style={styles.headerText}>
        <Text style={[styles.title, { color: colors.accent }]} accessibilityRole="header">
          🧾 {t("billingHistory") ?? "Billing History"}
        </Text>
        <Text style={[styles.subtitle, { color: colors.textSecondary }]}>
          {t("billingHistoryDesc") ?? "Your subscription payment invoices"}
        </Text>
      </View>

      {state === "loading" && (
        <View style={styles.centered} accessibilityLiveRegion="polite">
          <ActivityIndicator size="large" color={colors.accent} />
          <Text style={[styles.loadingText, { color: colors.textSecondary }]}>
            {t("loadingInvoices") ?? "Loading your invoices…"}
          </Text>
        </View>
      )}

      {state === "error" && (
        <View style={styles.centered}>
          <Ionicons name="cloud-offline-outline" size={40} color={colors.textSecondary} />
          <Text style={[styles.emptyTitle, { color: colors.text }]}>
            {t("billingLoadError") ?? "Couldn't load billing history"}
          </Text>
          <Text style={[styles.emptyHint, { color: colors.textSecondary }]}>
            {t("billingLoadErrorHint") ?? "Check your connection and try again."}
          </Text>
          <TouchableOpacity
            style={[styles.retryBtn, { backgroundColor: colors.accent }]}
            onPress={loadFirstPage}
            accessibilityRole="button"
            accessibilityLabel={t("retry") ?? "Retry"}
          >
            <Text style={styles.retryBtnText}>{t("retry") ?? "Retry"}</Text>
          </TouchableOpacity>
        </View>
      )}

      {state === "ready" && invoices.length === 0 && (
        <View style={styles.centered}>
          <Ionicons name="receipt-outline" size={40} color={colors.textSecondary} />
          <Text style={[styles.emptyTitle, { color: colors.text }]}>
            {t("noInvoicesYet") ?? "No invoices yet"}
          </Text>
          <Text style={[styles.emptyHint, { color: colors.textSecondary }]}>
            {t("noInvoicesHint") ?? "Your subscription payment invoices will appear here after a successful payment."}
          </Text>
        </View>
      )}

      {state === "ready" && invoices.length > 0 && (
        <FlatList
          data={invoices}
          keyExtractor={(item) => item.invoiceId}
          renderItem={renderItem}
          contentContainerStyle={styles.listContent}
          showsVerticalScrollIndicator={false}
          onEndReachedThreshold={0.4}
          onEndReached={loadNextPage}
          ListFooterComponent={
            loadingMore ? (
              <View style={styles.footerRow}>
                <ActivityIndicator size="small" color={colors.accent} />
              </View>
            ) : pageError ? (
              <TouchableOpacity
                style={[styles.footerRetry, { borderColor: colors.accent }]}
                onPress={loadNextPage}
                accessibilityRole="button"
              >
                <Text style={[styles.footerRetryText, { color: colors.accent }]}>
                  {t("retryLoadMore") ?? "Couldn't load more — tap to retry"}
                </Text>
              </TouchableOpacity>
            ) : !hasMore ? (
              <Text style={[styles.endText, { color: colors.textSecondary }]}>
                {t("endOfBillingHistory") ?? "That's your full billing history"}
              </Text>
            ) : null
          }
        />
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  headerText: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
  title: { fontSize: 26, fontWeight: "800", marginBottom: 4 },
  subtitle: { fontSize: 13, fontWeight: "500" },

  centered: { flex: 1, justifyContent: "center", alignItems: "center", gap: 10, paddingHorizontal: 32 },
  loadingText: { fontSize: 14, fontWeight: "500" },
  emptyTitle: { fontSize: 17, fontWeight: "800", marginTop: 4, textAlign: "center" },
  emptyHint: { fontSize: 13, fontWeight: "500", textAlign: "center", lineHeight: 19 },
  retryBtn: { marginTop: 8, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  retryBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },

  listContent: { paddingHorizontal: 20, paddingBottom: 32, gap: 10 },
  card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 6 },
  cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  planName: { fontSize: 15, fontWeight: "800", flexShrink: 1 },
  statusPill: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 20 },
  statusText: { fontSize: 11, fontWeight: "700" },
  invoiceNumber: { fontSize: 12, fontWeight: "500" },
  cardBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 2 },
  date: { fontSize: 12, fontWeight: "500" },
  amount: { fontSize: 17, fontWeight: "800" },

  footerRow: { paddingVertical: 16, alignItems: "center" },
  footerRetry: { marginTop: 4, paddingVertical: 12, borderRadius: 12, borderWidth: 1, alignItems: "center" },
  footerRetryText: { fontSize: 13, fontWeight: "700" },
  endText: { textAlign: "center", fontSize: 12, fontWeight: "500", paddingVertical: 16 },
});
